### PR TITLE
Use default spacing 1 for compatibility with FreeSurfer.

### PR DESCRIPTION
**Pull request by mu40**

### CODE REVIEW

**Comment by yhuang43** [comment]
Jackson/Avnish, the change is to make sure the output warp.mgz works with 'mri_convert -at' - the spacing is expected to be non-zero.

**Review by jnolan14 — COMMENTED** [review]
Looks ok to me.

**Comment by yhuang43** [comment]
The spacing corresponds to the 'spacing' field in struct GCA_MORPH (defined in include/gcamorph.h). It can't be 0. 

This is the fix on Freesurfer side when it reads warp.mgz - https://github.com/freesurfer/freesurfer/commit/f5cb17a8fc0a1b880dcb02be8e4d0889836dd01a

The PR is to fix on Surfa when it outputs warp.mgz

**Review by jnolan14 — APPROVED** [review]
Looks good

**Pull request merged**
